# Generated by Django 2.0.2 on 2018-02-25 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180225_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 25, 16, 2, 43, 647920, tzinfo=utc)),
        ),
    ]
